### ISSUE TITLE
difference between this typings and @types/mongodb

### ISSUE THREAD

**Issue by pleerock** [Think7/typings-mongodb#8]
What is the difference between this package and `@types/mongodb`? Since all packages now should be installed via `@types/` is there any strategy to merge this package into `@types/mongodb`?

**Comment by CaselIT** [comment]
This version can be used with https://github.com/typings/typings.
It's more or less in sync with the version on DefinitelyTyped.

I have to update it with the new generics that where added on DefinitelyTyped.

**Comment by pleerock** [comment]
Thanks for info

**Comment by pleerock** [comment]
btw is there any particular reason to continue to use `typings`. Ive migrated from it a few month ago, and thought new `@types/` system can completely replace it.

**Comment by CaselIT** [comment]
It has some advantages, but for the most part I think `@types/` can replace it completely.
